import json
import os
import subprocess

questions = [
    # --- HTML Basics & Structure (Ch 01-04) ---
    {
        "Question Text": "Хто є творцем мови HTML і в якому році з'явився перший веб-сайт?\n```html\n<!-- Перший сайт був присвячений Всесвітній павутині -->\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Брендан Ейх, 1995 рік",
        "Option 2": "Тім Бернерс-Лі, 1991 рік",
        "Option 3": "Хокон Віум Лі, 1994 рік",
        "Option 4": "Денніс Рітчі, 1989 рік",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Тім Бернерс-Лі винайшов HTML у CERN для обміну науковими документами. Перший веб-сайт з'явився 6 серпня 1991 року."
    },
    {
        "Question Text": "Вам потрібно швидко згенерувати таку структуру тегів за допомогою Emmet:\n```html\n<ul>\n    <li><a href=\"\"></a></li>\n    <li><a href=\"\"></a></li>\n    <li><a href=\"\"></a></li>\n</ul>\n```\nЯку абревіатуру слід ввести у VS Code?",
        "Question Type": "Multiple Choice",
        "Option 1": "ul+li*3+a",
        "Option 2": "ul>li*3>a",
        "Option 3": "ul(li>a)*3",
        "Option 4": "ul>li>a*3",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Знак `>` вказує на вкладеність (дитина), а `*3` повторює елемент `li` тричі разом з його дитиною `a`."
    },
    {
        "Question Text": "Які файли підпадають під дію локальних налаштувань (Workspace Settings) у файлі `.vscode/settings.json`?\n```json\n{\n  \"editor.formatOnSave\": true\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Усі проєкти, відкриті у VS Code на цьому комп'ютері",
        "Option 2": "Лише файли у поточній відкритій робочій папці (проєкті)",
        "Option 3": "Лише файли з розширенням .json",
        "Option 4": "Лише файли в папці .vscode",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Workspace Settings застосовуються виключно до поточної робочої папки (проєкту) і зберігаються в `.vscode/settings.json`."
    },
    {
        "Question Text": "Для чого використовується декларація `<!DOCTYPE html>` на самому початку HTML-документа?\n```html\n<!DOCTYPE html>\n<html>\n...\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Вона вказує браузеру, що документ використовує кодування UTF-8",
        "Option 2": "Вона повідомляє браузеру версію мови HTML (зокрема HTML5) для запобігання переходу в режим сумісності (Quirks Mode)",
        "Option 3": "Вона автоматично підключає базові CSS стилі",
        "Option 4": "Вона є обов'язковим парним тегом для завершення документа",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`<!DOCTYPE html>` вказує браузеру, що документ відповідає стандарту HTML5, і запускає рендеринг у режимі відповідності стандартам (Standards Mode)."
    },
    {
        "Question Text": "Які з наведених тегів дозволено розміщувати всередині елемента `<head>`?\n```html\n<head>\n    <!-- Що може бути тут? -->\n</head>\n```",
        "Question Type": "Checkbox",
        "Option 1": "<meta>",
        "Option 2": "<li>",
        "Option 3": "<link>",
        "Option 4": "<script>",
        "Option 5": "<img>",
        "Correct Answer": "1,3,4",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Всередині `<head>` розміщуються метадані: `<title>`, `<meta>`, `<link>`, `<style>`, `<script>`. Теги `<li>` та `<img>` призначені лише для `<body>`."
    },
    {
        "Question Text": "Який з наведених HTML-елементів за замовчуванням є рядковим (inline)?\n```html\n<!-- Оберіть тег із рядковим типом відображення -->\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "<div>",
        "Option 2": "<p>",
        "Option 3": "<span>",
        "Option 4": "<h1>",
        "Option 5": "",
        "Correct Answer": "3",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`<span>` — це рядковий (inline) елемент. Теги `<div>`, `<p>`, `<h1>` є блочними (block) елементами за замовчуванням."
    },
    {
        "Question Text": "Яка рекомендація щодо використання заголовка `<h1>` на одній веб-сторінці є найбільш критичною для SEO?\n```html\n<h1>Головний заголовок</h1>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Сторінка має містити щонайменше три заголовки <h1>",
        "Option 2": "Сторінка повинна мати рівно один заголовок <h1>, що відображає основну суть сторінки",
        "Option 3": "Заголовки <h1> мають використовуватися замість параграфів <p> для збільшення шрифту",
        "Option 4": "Тег <h1> обов'язково повинен містити атрибут href",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Згідно з найкращими практиками SEO та семантики, кожна сторінка повинна мати лише один заголовок `<h1>`, який описує її головну тему."
    },
    {
        "Question Text": "Який атрибут і значення використовуються для того, щоб посилання відкривалося в новій вкладці браузера?\n```html\n<a href=\"https://google.com\">Пошук</a>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "target=\"_blank\"",
        "Option 2": "rel=\"newtab\"",
        "Option 3": "target=\"_new\"",
        "Option 4": "open=\"blank\"",
        "Option 5": "",
        "Correct Answer": "1",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Атрибут `target=\"_blank\"` вказує браузеру відкрити пов'язаний документ у новому вікні або новій вкладці."
    },
    {
        "Question Text": "Ваша поточна сторінка знаходиться за адресою `site.com/pages/index.html`. Зображення лежить у `site.com/images/logo.png`. Який відносний шлях треба вказати в атрибуті `src`?\n```html\n<img src=\"\" alt=\"Логотип\">\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "./images/logo.png",
        "Option 2": "../images/logo.png",
        "Option 3": "images/logo.png",
        "Option 4": "../../images/logo.png",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "`../` піднімає нас на один рівень вгору (з папки `pages` до кореня), а далі ми переходимо в папку `images/logo.png`."
    },
    {
        "Question Text": "Яка основна мета використання атрибута `alt` у тегу `<img>`?\n```html\n<img src=\"avatar.png\" alt=\"Фото профілю\">\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Відображення підказки при наведенні курсору на зображення",
        "Option 2": "Забезпечення доступності (передачі тексту програмам зчитування екрана) та відображення альтернативного тексту, якщо зображення не завантажилось",
        "Option 3": "Задання стилю рамки навколо зображення",
        "Option 4": "Кешування зображення в браузері",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Атрибут `alt` є критичним для доступності (screen readers) і показує текст користувачам, у яких вимкнено або не завантажилося зображення."
    },
    {
        "Question Text": "Проаналізуйте код таблиці:\n```html\n<table>\n  <tr>\n    <td colspan=\"2\">Осередок A</td>\n    <td>Осередок B</td>\n  </tr>\n  <tr>\n    <td>Осередок C</td>\n    <td>Осередок D</td>\n    <td>Осередок E</td>\n  </tr>\n</table>\n```\nСкільки колонок (стовпців) має ця таблиця за своєю структурою?",
        "Question Type": "Multiple Choice",
        "Option 1": "2 стовпці",
        "Option 2": "3 стовпці",
        "Option 3": "4 стовпці",
        "Option 4": "5 стовпців",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Перший рядок містить осередки з `colspan=\"2\"` (об'єднує 2 колонки) + 1 звичайний осередок = 3 колонки. Другий рядок містить 3 окремі осередки, що підтверджує структуру на 3 колонки."
    },
    {
        "Question Text": "Які теги використовуються для створення списку визначень (Description List) в HTML?\n```html\n<!-- Потрібно створити термін та його опис -->\n```",
        "Question Type": "Checkbox",
        "Option 1": "<dl>",
        "Option 2": "<dt>",
        "Option 3": "<dd>",
        "Option 4": "<list>",
        "Option 5": "<li>",
        "Correct Answer": "1,2,3",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Список визначень створюється за допомогою тегу `<dl>` (description list), де `<dt>` описує термін (description term), а `<dd>` — його опис (description details)."
    },

    # --- HTML Forms & Multimedia (Ch 05-07) ---
    {
        "Question Text": "Який `type` для тегу `<input>` забезпечує вбудовану валідацію введеного користувачем URL-посилання?\n```html\n<input type=\"\" name=\"website\">\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "url",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`<input type=\"url\">` автоматично перевіряє, чи введений текст є валідним URL-посиланням, перед відправкою форми."
    },
    {
        "Question Text": "Яка головна відмінність між методами `GET` та `POST` при відправці форми на сервер?\n```html\n<form method=\"GET\"> vs <form method=\"POST\">\n```",
        "Question Type": "Checkbox",
        "Option 1": "GET передає дані форми через URL як параметри запиту.",
        "Option 2": "POST ховає дані у тіло HTTP-запиту, що робить його безпечнішим для паролів.",
        "Option 3": "GET дозволяє передавати файли великого об'єму.",
        "Option 4": "Запити POST можна кешувати і додавати в закладки браузера.",
        "Option 5": "GET має обмеження на об'єм даних, що передаються.",
        "Correct Answer": "1,2,5",
        "Time in seconds": "60",
        "Image Link": "",
        "Answer explanation": "GET додає дані до URL, має обмеження довжини і легко кешується. POST надсилає дані у тілі запиту, підходить для чутливих даних (паролі) та великих об'ємів."
    },
    {
        "Question Text": "Який спосіб є правильним для пов'язування тексту опису `<label>` з полем введення `<input>`?\n```html\n<!-- Оберіть правильні варіанти зв'язку -->\n```",
        "Question Type": "Checkbox",
        "Option 1": "<label for=\"email-field\">Email</label> <input id=\"email-field\" type=\"email\">",
        "Option 2": "<label>Email <input type=\"email\"></label>",
        "Option 3": "<label name=\"email\">Email</label> <input name=\"email\" type=\"email\">",
        "Option 4": "<label id=\"email\">Email</label> <input for=\"email\" type=\"email\">",
        "Option 5": "",
        "Correct Answer": "1,2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Зв'язати label з input можна через атрибути `for` (у label) та `id` (у input), або вклавши input безпосередньо всередину тегу label."
    },
    {
        "Question Text": "Яка CSS-властивість дозволяє заборонити користувачу самостійно розтягувати поле текстової області `<textarea>` на сторінці?\n```html\n<textarea style=\"\"></textarea>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "user-select: none;",
        "Option 2": "resize: none;",
        "Option 3": "overflow: hidden;",
        "Option 4": "display: fixed;",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `resize: none;` повністю вимикає інтерфейсний куточок зміни розміру `<textarea>` у браузерах."
    },
    {
        "Question Text": "Який семантичний тег згідно зі стандартом HTML5 найкраще підходить для представлення незалежного, самодостатнього розділу контенту (наприклад, статті в блозі або новини)?\n```html\n<section>\n  <!-- Який тег краще використати всередині? -->\n</section>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "<aside>",
        "Option 2": "<main>",
        "Option 3": "<article>",
        "Option 4": "<div>",
        "Option 5": "",
        "Correct Answer": "3",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Тег `<article>` призначений для самостійного контенту, який можна поширювати або перевикористовувати незалежно від решти сайту."
    },
    {
        "Question Text": "Який семантичний тег HTML5 описує бічну панель (sidebar) або контент, який опосередковано пов'язаний з основним вмістом сторінки?\n```html\n<!-- Оберіть тег для додаткового контенту -->\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "<section>",
        "Option 2": "<aside>",
        "Option 3": "<footer>",
        "Option 4": "<nav>",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Тег `<aside>` використовується для інформації, що стоїть окремо від головного матеріалу (наприклад, списку категорій, бічної реклами)."
    },
    {
        "Question Text": "Як правильно надати кілька альтернативних файлів відео різних форматів для нативного програвача `<video>`, щоб забезпечити кросбраузерність?\n```html\n<video controls>\n    <!-- Як вказати шляхи до файлів? -->\n</video>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Вказати кілька атрибутів src: <video src=\"v.mp4\" src=\"v.webm\">",
        "Option 2": "Використати вкладені теги <source> з атрибутами src та type",
        "Option 3": "Записати файли через кому: <video src=\"v.mp4, v.webm\">",
        "Option 4": "Браузери не підтримують альтернативні формати відео без JavaScript",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Вкладені елементи `<source>` дозволяють браузеру обрати перший підтримуваний формат файлу зі списку."
    },
    {
        "Question Text": "У чому полягає фундаментальна різниця між технологіями SVG та Canvas в HTML?\n```html\n<svg> vs <canvas>\n```",
        "Question Type": "Checkbox",
        "Option 1": "SVG працює з векторною графікою та зберігає фігури в DOM-дереві.",
        "Option 2": "Canvas є растровим та малює пікселі за допомогою JavaScript API.",
        "Option 3": "Canvas масштабується без втрати якості на будь-яких екранах.",
        "Option 4": "Стилізувати елементи SVG можна за допомогою стандартного CSS.",
        "Option 5": "SVG гірше підходить для ігор з великою кількістю динамічних об'єктів.",
        "Correct Answer": "1,2,4,5",
        "Time in seconds": "60",
        "Image Link": "",
        "Answer explanation": "SVG векторний, входить в DOM і підтримує CSS стилізацію. Canvas — це растровий піксельний буфер, який малюється через JS. При масштабуванні Canvas може втрачати чіткість, але він набагато швидший для складної анімації (ігор)."
    },
    {
        "Question Text": "Який атрибут використовується в тегу `<iframe>` для задання адреси веб-сторінки, яку необхідно вмонтувати?\n```html\n<iframe src=\"https://example.com\"></iframe>\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "src",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Атрибут `src` (source) визначає URL-адресу зовнішньої сторінки, яка завантажується всередину фрейму."
    },

    # --- SEO & Microdata (Ch 08) ---
    {
        "Question Text": "Яке призначення має наступний мета-тег в області `<head>`?\n```html\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Він вказує пошуковим роботам індексувати мобільну версію сайту",
        "Option 2": "Він адаптує ширину області перегляду під фізичний екран пристрою та задає початковий масштаб 100% для запобігання автоматичного зменшення шрифтів",
        "Option 3": "Він забороняє користувачу повертати екран на мобільному пристрої",
        "Option 4": "Він автоматично переводить пікселі в rem-одиниці",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Мета-тег `viewport` керує відображенням на мобільних пристроях. `width=device-width` робить область перегляду рівною ширині пристрою, а `initial-scale=1.0` запобігає зуму за замовчуванням."
    },
    {
        "Question Text": "Який префікс вказується в атрибуті `property` мета-тегів для налаштування прев'ю посилання в соціальних мережах за стандартом Open Graph?\n```html\n<meta property=\"og:title\" content=\"...\">\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "og:",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Для стандарту Open Graph використовуються властивості з префіксом `og:` (наприклад, `og:title`, `og:image`, `og:description`)."
    },
    {
        "Question Text": "Які атрибути використовуються для розмітки структурованих даних (Microdata) відповідно до Schema.org прямо в HTML-тегах?\n```html\n<div itemscope itemtype=\"https://schema.org/Product\">\n  <span itemprop=\"name\">Товар</span>\n</div>\n```",
        "Question Type": "Checkbox",
        "Option 1": "itemscope",
        "Option 2": "itemtype",
        "Option 3": "itemprop",
        "Option 4": "itemdata",
        "Option 5": "schema-type",
        "Correct Answer": "1,2,3",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Стандарт Microdata використовує атрибути `itemscope` (створює об'єкт), `itemtype` (визначає його тип за Schema.org) та `itemprop` (визначає властивості об'єкта)."
    },

    # --- CSS Selectors, Box Model & Sizing (Ch 09-10a) ---
    {
        "Question Text": "Проаналізуйте CSS селектори. Який із них має НАЙВИЩИЙ пріоритет (специфічність)?\n```css\n/* Selector 1 */  ul li a\n/* Selector 2 */  .menu-list a\n/* Selector 3 */  #menu a\n/* Selector 4 */  #menu .active-link\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "ul li a",
        "Option 2": ".menu-list a",
        "Option 3": "#menu a",
        "Option 4": "#menu .active-link",
        "Option 5": "",
        "Correct Answer": "4",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Специфічність селектора #menu .active-link дорівнює 1 ID (100) + 1 Клас (10) = 110. Це більше, ніж у інших (100 для `#menu a`, 10 для `.menu-list a`, і 3 для `ul li a`)."
    },
    {
        "Question Text": "Які з наведених CSS-записів відносяться до псевдоелементів (pseudo-elements)?\n```css\n/* Виберіть псевдоелементи */\n```",
        "Question Type": "Checkbox",
        "Option 1": "::before",
        "Option 2": ":hover",
        "Option 3": "::first-letter",
        "Option 4": ":nth-child(2)",
        "Option 5": "::placeholder",
        "Correct Answer": "1,3,5",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Псевдоелементи мають подвійну двокрапку `::` і створюють віртуальні частини елемента. Псевдокласи (`:hover`, `:nth-child`) мають одну двокрапку і описують стан елемента."
    },
    {
        "Question Text": "Який селектор вибере всі посилання, значення атрибута `href` яких починається з протоколу `https`?\n```css\n/* Оберіть правильний атрибутивний селектор */\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "a[href*=\"https\"]",
        "Option 2": "a[href^=\"https\"]",
        "Option 3": "a[href$=\"https\"]",
        "Option 4": "a[href~=\"https\"]",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Символ `^=` вибирає елементи, значення атрибута яких починається з вказаного рядка. `*=` шукає входження у будь-якому місці, а `$=` перевіряє закінчення рядка."
    },
    {
        "Question Text": "Який елемент буде обрано за допомогою селектора сусідніх елементів `div + p`?\n```html\n<div>Блок 1</div>\n<p>Параграф 2</p>\n<p>Параграф 3</p>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Усі параграфи <p> на сторінці",
        "Option 2": "Тільки Параграф 2, оскільки він є першим наступним сусідом елемента <div>",
        "Option 3": "Параграф 2 та Параграф 3",
        "Option 4": "Елемент <div>, який містить параграф всередині",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Сусідній селектор `+` вибирає лише один безпосередньо наступний елемент, що знаходиться на тому ж рівні вкладеності."
    },
    {
        "Question Text": "Яка поведінка очікується від властивості `color` для спадкоємця, якщо прописано значення `inherit`?\n```css\n.child {\n  color: inherit;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Елемент візьме колір за замовчуванням браузера",
        "Option 2": "Елемент примусово візьме значення властивості color від свого безпосереднього батьківського елемента",
        "Option 3": "Колір стане прозорим",
        "Option 4": "Колір буде інвертований",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Ключове слово `inherit` змушує властивість набувати такого ж обчисленого значення, як і у батьківського елемента."
    },
    {
        "Question Text": "Яка модель обчислення розмірів елемента діє за замовчуванням у браузерах?\n```css\n/* Яке значення має box-sizing за замовчуванням? */\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "border-box",
        "Option 2": "content-box",
        "Option 3": "padding-box",
        "Option 4": "margin-box",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Стандартним значенням для `box-sizing` є `content-box`. При ньому властивості `width`/`height` задають розмір виключно контентної області."
    },
    {
        "Question Text": "Елемент має такі CSS-стилі:\n```css\n.box {\n  box-sizing: border-box;\n  width: 200px;\n  padding: 20px;\n  border: 5px solid black;\n  margin: 10px;\n}\n```\nЯкою буде повна фізична ширина (`width`) цього блоку в макеті (без урахування margin)?",
        "Question Type": "Multiple Choice",
        "Option 1": "200px",
        "Option 2": "250px",
        "Option 3": "150px",
        "Option 4": "220px",
        "Option 5": "",
        "Correct Answer": "1",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "При `box-sizing: border-box` внутрішні відступи (padding) та межі (border) входять у загальну ширину. Тож загальна ширина елемента залишається рівною заданій властивості `width` — 200px."
    },
    {
        "Question Text": "За яких умов відбувається схлопування вертикальних маргінів (Margin Collapse) в CSS?\n```css\n/* margin-top та margin-bottom сусідніх елементів */\n```",
        "Question Type": "Checkbox",
        "Option 1": "Схлопування відбувається між сусідніми блочними елементами у звичайному потоці документа.",
        "Option 2": "Схлопування відбувається між флекс-елементами всередині flex-контейнера.",
        "Option 3": "Схлопування відбувається між порожніми блоками без границь, паддінгів та контенту.",
        "Option 4": "Схлопування відбувається між елементами з абсолютною позицією (position: absolute).",
        "Option 5": "",
        "Correct Answer": "1,3",
        "Time in seconds": "60",
        "Image Link": "",
        "Answer explanation": "Схлопування маргінів діє лише на блочні елементи у нормальному потоці (in-flow). Воно не діє на флекс/грід елементи, абсолютне позиціонування та плаваючі блоки (floats)."
    },
    {
        "Question Text": "У чому полягає різниця між значеннями `width: 100%` та `width: 100vw` для блочного елемента?\n```css\n.element-1 { width: 100%; }\n.element-2 { width: 100vw; }\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Різниці немає, це ідентичні записи",
        "Option 2": "`100%` вираховується від ширини батьківського контейнера, а `100vw` — від повної ширини в'юпорта (включаючи смугу прокрутки)",
        "Option 3": "`100vw` обмежується максимальною шириною мобільних пристроїв, а `100%` — ні",
        "Option 4": "`100%` включає в себе margin, а `100vw` ніколи не враховує відступи",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "`100%` прив'язаний до ширини батьківського блоку. `100vw` (viewport width) завжди дорівнює повній ширині вікна браузера. Якщо на сторінці є вертикальний скролбар, елемент з `100vw` може викликати горизонтальну прокрутку, бо скролбар входить у ширину в'юпорта."
    },
    {
        "Question Text": "Як поведе себе елемент, якщо йому задати властивість `width: max-content`?\n```css\n.box {\n  width: max-content;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Він займе всю доступну ширину батьківського елемента",
        "Option 2": "Він стиснеться до мінімально можливої ширини, де слова переносяться на нові рядки",
        "Option 3": "Він розшириться рівно настільки, щоб вмістити весь свій текст в один рядок без переносу (якщо це можливо)",
        "Option 4": "Він автоматично прийме ширину 100% екрана",
        "Option 5": "",
        "Correct Answer": "3",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "`max-content` задає блоку ідеальну ширину, необхідну для відображення всього вмісту без переносу рядків."
    },
    {
        "Question Text": "Яка CSS-властивість задає внутрішні відступи від контенту до межі елемента?\n```css\n.element {\n  /* Яку властивість записати тут? */: 20px;\n}\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "padding",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `padding` керує простором всередині блоку (між контентом та рамкою border)."
    },
    {
        "Question Text": "Який псевдоклас використовується для вибору та стилізації елемента у момент, коли на нього наведено курсор миші?\n```css\na:hover {\n  color: red;\n}\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": ":hover",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Псевдоклас `:hover` спрацьовує, коли користувач наводить вказівник миші на елемент."
    },

    # --- CSS Typography, Colors & Effects (Ch 11-12b) ---
    {
        "Question Text": "Яка основна відмінність між одиницями виміру `em` та `rem` у CSS?\n```css\n.box-1 { font-size: 2em; }\n.box-2 { font-size: 2rem; }\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "`em` вираховується від розміру шрифту батьківського елемента, а `rem` — виключно від розміру шрифту кореневого елемента (<html>)",
        "Option 2": "`rem` залежить від ширини екрана, а `em` — статичний",
        "Option 3": "`em` можна використовувати лише для внутрішніх відступів padding, а `rem` — лише для шрифтів",
        "Option 4": "`rem` підтримується лише на мобільних пристроях",
        "Option 5": "",
        "Correct Answer": "1",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "`em` є відносною одиницею, яка бере за основу розмір шрифту безпосереднього батька (або власного, якщо задається не для font-size). `rem` (root em) завжди бере за основу базовий розмір шрифту кореневого елемента `html`."
    },
    {
        "Question Text": "Чому для визначення висоти рядка (`line-height`) рекомендовано використовувати безрозмірні коефіцієнти (наприклад, `1.5`) замість абсолютних значень у пікселях?\n```css\nbody {\n  line-height: 1.5; /* Чому це краще за 24px? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Безрозмірний коефіцієнт не успадковується дочірніми елементами",
        "Option 2": "Він автоматично масштабується пропорційно розміру шрифту (font-size) кожного окремого дочірнього елемента",
        "Option 3": "Це вимога стандарту W3C, інакше сторінка не пройде валідацію",
        "Option 4": "Він пришвидшує рендеринг тексту у браузері",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Коли `line-height` задано числом без одиниць, спадкоємці множать це число на свій власний `font-size`. Якщо вказати фіксовані `24px` на батьку, а нащадок збільшить свій шрифт до `32px` — текст наповзе один на одного."
    },
    {
        "Question Text": "Які числові значення властивості `font-weight` відповідають стандартним накресленням шрифту `normal` та `bold`?\n```css\n.text {\n  font-weight: 400; /* Яке це накреслення? */\n}\n```",
        "Question Type": "Checkbox",
        "Option 1": "300 відповідає normal",
        "Option 2": "400 відповідає normal",
        "Option 3": "700 відповідає bold",
        "Option 4": "900 відповідає bold",
        "Option 5": "",
        "Correct Answer": "2,3",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "За специфікацією, значення `400` еквівалентне `normal`, а `700` відповідає `bold`."
    },
    {
        "Question Text": "Який колір буде отримано при використанні такого запису моделі HSL?\n```css\n.bg {\n  background-color: hsl(0, 100%, 50%);\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Зелений",
        "Option 2": "Синій",
        "Option 3": "Червоний",
        "Option 4": "Чорний",
        "Option 5": "",
        "Correct Answer": "3",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "У колірній моделі HSL перший параметр (Hue) визначає кут на колірному колі. `0` градусів відповідає чистій червоній барві."
    },
    {
        "Question Text": "Який параметр у форматі `rgba(0, 0, 0, 0.4)` відповідає за напівпрозорість кольору?\n```css\n.overlay {\n  background-color: rgba(0, 0, 0, 0.4);\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Перший параметр 0",
        "Option 2": "Другий параметр 0",
        "Option 3": "Останній параметр 0.4",
        "Option 4": "Всі параметри сумарно",
        "Option 5": "",
        "Correct Answer": "3",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Четвертий параметр в `rgba()` — це канал альфа (Alpha), який визначає рівень прозорості від `0` (абсолютно прозорий) до `1` (повністю непрозорий)."
    },
    {
        "Question Text": "Які з наведених тверджень описують поведінку `background-size` зі значеннями `cover` та `contain`?\n```css\n/* cover vs contain */\n```",
        "Question Type": "Checkbox",
        "Option 1": "`cover` масштабує зображення так, щоб повністю закрити область тла, навіть якщо це призведе до обрізання частини картинки.",
        "Option 2": "`contain` масштабує зображення так, щоб воно повністю вмістилося в область, залишаючи порожні зони по боках або зверху/знизу, якщо пропорції не збігаються.",
        "Option 3": "`cover` завжди зберігає пропорції картинки, а `contain` деформує та розтягує її.",
        "Option 4": "Обидва значення не масштабують фонове зображення.",
        "Option 5": "",
        "Correct Answer": "1,2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Обидва режими зберігають оригінальні пропорції (aspect ratio). Але `cover` прагне повністю заповнити контейнер (картинка може обрізатися), а `contain` прагне показати зображення повністю без обрізання (може з'явитися пусте тло)."
    },
    {
        "Question Text": "Як правильно задати діагональний лінійний градієнт від верхнього лівого кутка до нижнього правого?\n```css\n.gradient-bg {\n  background: linear-gradient();\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "linear-gradient(to bottom right, red, blue)",
        "Option 2": "linear-gradient(to top left, red, blue)",
        "Option 3": "linear-gradient(diagonal, red, blue)",
        "Option 4": "linear-gradient(45deg, to bottom, red, blue)",
        "Option 5": "",
        "Correct Answer": "1",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Напрямок градієнта `to bottom right` означає рух від протилежного кутка (top left) до вказаного (bottom right)."
    },
    {
        "Question Text": "Вам задано стиль тіні для блоку:\n```css\n.card {\n  box-shadow: 2px 4px 6px rgba(0, 0, 0, 0.3);\n}\n```\nЗа що відповідає третій числовий параметр `6px`?",
        "Question Type": "Multiple Choice",
        "Option 1": "Зсув тіні по горизонталі (X)",
        "Option 2": "Зсув тіні по вертикалі (Y)",
        "Option 3": "Радіус розмиття (Blur radius)",
        "Option 4": "Радіус розтягування тіні (Spread radius)",
        "Option 5": "",
        "Correct Answer": "3",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Параметри `box-shadow` йдуть у черговості: offset-x, offset-y, blur-radius, spread-radius (опціонально), колір. Тож `6px` — це радіус розмиття тіні."
    },
    {
        "Question Text": "Яка CSS-властивість та значення перетворюють кольорове зображення на повністю чорно-біле?\n```css\nimg {\n  /* Який фільтр застосувати? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "filter: invert(100%);",
        "Option 2": "filter: grayscale(100%);",
        "Option 3": "filter: blur(10px);",
        "Option 4": "filter: opacity(0%);",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Фільтр `grayscale(100%)` повністю знебарвлює картинку, роблячи її відтінками сірого (чорно-білою)."
    },

    # --- CSS Flexbox (Ch 13-14) ---
    {
        "Question Text": "У вас є флекс-контейнер з вертикальною головною віссю:\n```css\n.container {\n  display: flex;\n  flex-direction: column;\n}\n```\nЯка властивість відповідає за вирівнювання його елементів по ГОРИЗОНТАЛІ (поперечній осі)?",
        "Question Type": "Multiple Choice",
        "Option 1": "justify-content",
        "Option 2": "align-items",
        "Option 3": "align-content",
        "Option 4": "flex-wrap",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Коли `flex-direction` встановлено в `column`, головна вісь спрямована вниз, а поперечна — вбік (горизонтально). Вирівнюванням по поперечній осі керує властивість `align-items`."
    },
    {
        "Question Text": "Що станеться з елементами флекс-контейнера за замовчуванням, якщо їх загальна ширина більша за ширину самого контейнера?\n```css\n.container {\n  display: flex;\n  /* flex-wrap не вказано */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Вони автоматично перенесуться на наступний рядок",
        "Option 2": "Вони будуть стискатися (якщо у них увімкнено flex-shrink) або вийдуть за межі контейнера без переносу",
        "Option 3": "Контейнер автоматично розшириться під розмір елементів",
        "Option 4": "Вони автоматично стануть невидимими",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "За замовчуванням `flex-wrap` має значення `nowrap`. Це означає, що елементи вишикуються в один рядок і будуть стискатися до ліміту своєї мінімальної ширини контенту."
    },
    {
        "Question Text": "Які значення властивості `justify-content` розподіляють вільний простір між або навколо флекс-елементів?\n```css\n.container {\n  display: flex;\n  justify-content: /* Що може бути тут? */;\n}\n```",
        "Question Type": "Checkbox",
        "Option 1": "space-between",
        "Option 2": "space-around",
        "Option 3": "space-evenly",
        "Option 4": "center",
        "Option 5": "stretch",
        "Correct Answer": "1,2,3",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "`space-between` розподіляє простір між елементами (крайні притиснуті), `space-around` додає однакові відступи по обидва боки кожного елемента, а `space-evenly` робить абсолютно однакові проміжки всюди."
    },
    {
        "Question Text": "Розберіть скорочений запис властивості flex для флекс-елемента:\n```css\n.item {\n  flex: 2 1 150px;\n}\n```\nЩо означають ці три параметри по порядку?",
        "Question Type": "Multiple Choice",
        "Option 1": "flex-shrink: 2, flex-grow: 1, flex-basis: 150px",
        "Option 2": "flex-grow: 2, flex-shrink: 1, flex-basis: 150px",
        "Option 3": "flex-basis: 2, flex-grow: 1, flex-shrink: 150px",
        "Option 4": "flex-grow: 2, flex-basis: 1, flex-shrink: 150px",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Властивість `flex` є shorthand-записом для трьох параметрів: спочатку `flex-grow` (жадібність зростання), потім `flex-shrink` (коефіцієнт стискання) і наприкінці `flex-basis` (базовий розмір)."
    },
    {
        "Question Text": "У чому відмінність між `flex-basis: 0` та `flex-basis: auto` при розрахунках вільного простору?\n```css\n.item {\n  flex-basis: /* 0 vs auto */;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Відмінностей немає, обидва записи діють однаково",
        "Option 2": "`flex-basis: 0` ігнорує розмір вмісту елемента при розрахунках і вважає його початкову ширину нульовою, а `flex-basis: auto` бере за основу розмір контенту елемента або його властивість width",
        "Option 3": "`flex-basis: auto` змушує елемент займати 100% екрана",
        "Option 4": "`flex-basis: 0` повністю приховує елемент зі сторінки",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "При `flex-basis: 0` елемент вважається таким, що не має базового розміру, і весь його розмір буде результатом розподілу вільного місця. При `auto` спочатку виділяється місце під контент, а потім ділиться залишок."
    },
    {
        "Question Text": "Яке значення властивості `order` за замовчуванням мають усі елементи флекс-контейнера?\n```css\n.item {\n  /* Яке значення order діє за замовчуванням? */\n}\n```",
        "Question Type": "Checkbox",
        "Option 1": "0",
        "Option 2": "1",
        "Option 3": "-1",
        "Option 4": "auto",
        "Option 5": "none",
        "Correct Answer": "1",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "За замовчуванням властивість `order` для всіх елементів має значення `0`. Через це зміна пріоритету відображення елемента на `-1` посуне його на початок, а `1` — в кінець."
    },
    {
        "Question Text": "Яка CSS-властивість дозволяє індивідуально вирівняти один конкретний флекс-елемент уздовж поперечної осі, перевизначаючи загальне значення `align-items` контейнера?\n```css\n.special-item {\n  /* Яку властивість записати тут? */: flex-end;\n}\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "align-self",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `align-self` застосовується безпосередньо до флекс-елемента і дозволяє змінити його вирівнювання по поперечній осі."
    },

    # --- CSS Grid (Ch 15-16) ---
    {
        "Question Text": "Контейнеру задано таку сітку:\n```css\n.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n}\n```\nЩо означає одиниця виміру `1fr`?",
        "Question Type": "Multiple Choice",
        "Option 1": "Один піксель відносно щільності екрана",
        "Option 2": "Одну гнучку частку (fraction) від усього вільного простору, який залишився в grid-контейнері",
        "Option 3": "Один відсоток від ширини батьківського елемента",
        "Option 4": "Фіксований розмір шрифту",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`fr` (fraction) — це гнучка одиниця виміру, яка вказує планувальнику Grid виділити пропорційну частку вільного простору контейнера."
    },
    {
        "Question Text": "Як змусити елемент Grid зайняти дві колонки сітки, починаючи з першої лінії?\n```css\n.grid-item {\n  /* Оберіть правильні варіанти запису */\n}\n```",
        "Question Type": "Checkbox",
        "Option 1": "grid-column: 1 / 3;",
        "Option 2": "grid-column: 1 / span 2;",
        "Option 3": "grid-column-start: 1; grid-column-end: span 2;",
        "Option 4": "grid-span: 2 starting 1;",
        "Option 5": "",
        "Correct Answer": "1,2,3",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Для об'єднання колонок можна вказати початкову та кінцеву лінії (`1 / 3`), або початкову та ключове слово span (`1 / span 2`), як у скороченому, так і в повному варіантах властивостей."
    },
    {
        "Question Text": "У вас описано шаблон сітки за допомогою областей:\n```css\n.container {\n  display: grid;\n  grid-template-areas:\n    \"header header\"\n    \"sidebar main\";\n}\n```\nЯк прикріпити дочірній елемент `.sidebar-nav` до області `sidebar`?",
        "Question Type": "Multiple Choice",
        "Option 1": "grid-area: \"sidebar\";",
        "Option 2": "grid-area: sidebar;",
        "Option 3": "grid-template-areas: sidebar;",
        "Option 4": "grid-column-name: sidebar;",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Щоб прив'язати елемент до іменованої області, використовується властивість `grid-area` з ім'ям області (без лапок)."
    },
    {
        "Question Text": "У чому різниця між використанням `auto-fill` та `auto-fit` у функції `repeat()` для створення адаптивної сітки?\n```css\ngrid-template-columns: repeat(auto-fill, minmax(200px, 1fr));\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Різниці немає, це синоніми",
        "Option 2": "`auto-fill` створює максимально можливу кількість колонок, навіть якщо вони залишаться порожніми, а `auto-fit` стискає порожні колонки до 0px, розширюючи заповнені колонки на всю ширину",
        "Option 3": "`auto-fit` дозволяє додавати нескінченно багато елементів в один рядок",
        "Option 4": "`auto-fill` працює лише з висотою, а `auto-fit` лише з шириною",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "`auto-fill` заповнює контейнер порожніми треками, якщо для них є місце. `auto-fit` після розміщення елементів схлопує невикористані треки, дозволяючи заповненим трекам зайняти весь вільний простір."
    },
    {
        "Question Text": "Яка поведінка очікується від сітки із вказаним правилом?\n```css\n.grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Вона створить колонки фіксованої ширини по 150px без адаптивності",
        "Option 2": "Вона автоматично розраховує кількість колонок шириною від 150px і розтягує їх до 1fr, переносячи елементи на наступний рядок при зменшенні простору без медіа-запитів",
        "Option 3": "Вона обмежить висоту рядків до 150px",
        "Option 4": "Вона викличе горизонтальну прокрутку при ширині екрана менше 150px",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Це класичний паттерн адаптивної Grid-сітки без медіа-запитів. Колонки будуть не менше 150px, а весь залишок розширюватиметься пропорційно. Коли ширина екрана зменшується і колонка не може бути 150px, елемент переноситься на новий рядок."
    },

    # --- CSS Positioning (Ch 17) ---
    {
        "Question Text": "Як поводиться елемент, якому задано властивість `position: relative`?\n```css\n.box {\n  position: relative;\n  top: 10px;\n  left: 20px;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Він виривається зі звичайного потоку і позиціонується відносно екрана браузера",
        "Option 2": "Він залишається у нормальному потоці документа, але зсувається відносно свого вихідного (початкового) положення, не впливаючи на розміщення інших елементів",
        "Option 3": "Він стає блочним і притискається до верху сторінки",
        "Option 4": "Він позиціонується відносно найближчого батьківського елемента з будь-яким позиціонуванням",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`position: relative` зсуває елемент відносно його нормального положення в потоці. Місце, яке елемент займав у потоці, резервується за ним, і сусідні елементи не зміщуються."
    },
    {
        "Question Text": "Елемент з `position: absolute` позиціонується відносно якого предка?\n```css\n.child {\n  position: absolute;\n  top: 0;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Завжди відносно вікна браузера (viewport)",
        "Option 2": "Відносно найближчого предка, позиціонування якого відрізняється від static (наприклад, relative, absolute, fixed)",
        "Option 3": "Завжди відносно свого безпосереднього батьківського тегу",
        "Option 4": "Відносно елемента <body>",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Абсолютно позиціонований елемент шукає вгору по дереву найближчого предка, що має властивість `position` з будь-яким значенням, крім `static` (за замовчуванням). Якщо такого немає, позиціонування буде відносно початкового контейнера (<html>)."
    },
    {
        "Question Text": "Чому елемент з властивостями `position: sticky; top: 0;` може НЕ залишатися прикріпленим при прокручуванні сторінки?\n```css\n.header {\n  position: sticky;\n  top: 0;\n}\n```",
        "Question Type": "Checkbox",
        "Option 1": "Один з батьківських елементів має властивість overflow: hidden, auto або scroll.",
        "Option 2": "Батьківський елемент має таку саму висоту, що й сам sticky-елемент (елементу немає куди ковзати всередині предка).",
        "Option 3": "Елемент має висоту 100% від екрана.",
        "Option 4": "Не вказано властивість top (чи інша сторона зсуву).",
        "Option 5": "",
        "Correct Answer": "1,2,4",
        "Time in seconds": "60",
        "Image Link": "",
        "Answer explanation": "Sticky працює лише в межах висоти свого батьківського елемента. Якщо батько завершився — sticky-елемент прокручується далі. Також робота блокується будь-якими батьківськими `overflow` (крім visible) та відсутністю координат прилипання (наприклад, `top: 0`)."
    },
    {
        "Question Text": "Чи буде діяти властивість `z-index` для елемента, який має позиціонування за замовчуванням?\n```css\n.card {\n  position: static;\n  z-index: 999;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Так, z-index працює на всіх елементах без винятку",
        "Option 2": "Ні, z-index діє виключно на позиціоновані елементи (relative, absolute, fixed, sticky), окрім static",
        "Option 3": "Так, але тільки якщо елемент є флекс-дитиною",
        "Option 4": "Ні, z-index працює тільки разом з opacity",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `z-index` не працює на елементах з `position: static` (це стандартний стан). Вона починає діяти лише після зміни позиціонування на relative, absolute тощо (або для грид/флекс дітей)."
    },

    # --- CSS Animations & Transitions (Ch 18) ---
    {
        "Question Text": "Вам потрібно зробити плавну анімацію зміни кольору кнопки при наведенні курсору. Який CSS-запис є правильним?\n```css\n.btn {\n  background-color: blue;\n  /* Як налаштувати перехід? */\n}\n.btn:hover {\n  background-color: red;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "transition: background-color 0.3s ease;",
        "Option 2": "transition-on: hover 0.3s;",
        "Option 3": "animate: color 300ms;",
        "Option 4": "transition: all hover 0.3s;",
        "Option 5": "",
        "Correct Answer": "1",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `transition` задається для базового стану елемента (не для псевдокласу `:hover`) і визначає властивість переходу, тривалість та функцію розподілу часу."
    },
    {
        "Question Text": "Які з наведених варіантів описують правильний синтаксис для оголошення ключових кадрів анімації у CSS?\n```css\n/* Як оголосити анімацію з назвою pulse? */\n```",
        "Question Type": "Checkbox",
        "Option 1": "@keyframes pulse { from { opacity: 1; } to { opacity: 0.5; } }",
        "Option 2": "@keyframes pulse { 0% { opacity: 1; } 100% { opacity: 0.5; } }",
        "Option 3": "@animation pulse { from { opacity: 1; } to { opacity: 0.5; } }",
        "Option 4": "@keyframes pulse { start { opacity: 1; } end { opacity: 0.5; } }",
        "Option 5": "",
        "Correct Answer": "1,2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Ключові кадри описуються за допомогою директиви `@keyframes`. Точки анімації можна задавати словами `from` / `to` або відсотками (від `0%` до `100%`)."
    },

    # --- CSS Responsive Media Queries (Ch 19-20) ---
    {
        "Question Text": "Як правильно написати медіа-запит у CSS для застосування стилів виключно на екранах шириною від 480px до 768px включно?\n```css\n/* Медіа запит для планшетів */\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "@media (min-width: 480px) and (max-width: 768px)",
        "Option 2": "@media (screen-width: 480px-768px)",
        "Option 3": "@media (width > 480px) or (width < 768px)",
        "Option 4": "@media inside (480px, 768px)",
        "Option 5": "",
        "Correct Answer": "1",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Оператор `and` об'єднує дві умови: мінімальну ширину `min-width: 480px` та максимальну ширину `max-width: 768px`."
    },
    {
        "Question Text": "Яке призначення має елемент `<picture>` в адаптивному HTML-верстанні?\n```html\n<picture>\n  <source media=\"(min-width: 800px)\" srcset=\"large.jpg\">\n  <img src=\"small.jpg\" alt=\"\">\n</picture>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Він автоматично перетворює будь-які зображення на векторний формат SVG",
        "Option 2": "Він служить контейнером для кількох джерел зображення, дозволяючи браузеру обирати різні файли залежно від медіа-умов (адаптивність картинки, art direction)",
        "Option 3": "Він додає рамку та підпис під картинкою",
        "Option 4": "Він пришвидшує завантаження картинок за допомогою штучного інтелекту",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Елемент `<picture>` дозволяє реалізувати гнучку адаптивність зображень: підбирати оптимальні формати (напр. WebP), розміри або взагалі змінювати обрізання картинки для мобільних екранів."
    },
    {
        "Question Text": "Яке значення властивості `object-fit` масштабує контент (наприклад, картинку) так, щоб він повністю заповнив контейнер із збереженням пропорцій, обрізаючи зайве, якщо співвідношення сторін відрізняються?\n```css\nimg {\n  width: 100%;\n  height: 300px;\n  object-fit: /* Що вказати тут? */;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "fill",
        "Option 2": "contain",
        "Option 3": "cover",
        "Option 4": "scale-down",
        "Option 5": "",
        "Correct Answer": "3",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`object-fit: cover` розтягує картинку для повного заповнення блоку, зберігаючи її пропорції. Частина картинки при цьому може бути обрізана."
    },
    {
        "Question Text": "Проаналізуйте CSS функцію clamp:\n```css\n.text {\n  font-size: clamp(1rem, 2.5vw, 2rem);\n}\n```\nЯким є мінімально можливий розмір шрифту для цього елемента?",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "1rem",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Функція `clamp(MIN, VAL, MAX)` приймає три значення: мінімальний поріг, гнучке значення і максимальний поріг. Тож мінімум дорівнює `1rem`."
    },

    # --- CSS Variables & Methodologies (Ch 21, 27) ---
    {
        "Question Text": "Де прийнято оголошувати глобальні CSS-змінні (custom properties), щоб вони були доступні по всій сторінці?\n```css\n/* Де оголосити змінну --primary-color? */\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Всередині селектора body",
        "Option 2": "У псевдокласі :root",
        "Option 3": "У правилі @keyframes",
        "Option 4": "В тегу <meta>",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Псевдоклас `:root` відповідає кореневому елементу документа (<html>). Оголошені в ньому змінні мають глобальну область видимості і успадковуються всіма елементами."
    },
    {
        "Question Text": "Який елемент назви класу за методологією BEM (Block Element Modifier) вказує на модифікатор?\n```css\n/* Приклади класів: */\n/* 1. .card__title */\n/* 2. .card--dark */\n/* 3. .card */\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "title у класі .card__title",
        "Option 2": "dark у класі .card--dark",
        "Option 3": "card у класі .card",
        "Option 4": "Усі варіанти є модифікаторами",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "У методології BEM елементи відокремлюються подвійним підкресленням `__`, а модифікатори (стани чи варіанти оформлення) — подвійним дефісом `--`."
    },
    {
        "Question Text": "Зміна яких CSS-властивостей змушує браузер ініціювати етап перерахунку геометрії та компонування елементів (Reflow/Layout) на сторінці?\n```css\n/* Які властивості викликають Reflow? */\n```",
        "Question Type": "Checkbox",
        "Option 1": "width / height",
        "Option 2": "margin / padding",
        "Option 3": "color / background-color",
        "Option 4": "opacity",
        "Option 5": "transform",
        "Correct Answer": "1,2",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Властивості, які впливають на геометрію блоків (`width`, `height`, `margin`, `padding`, `display`), викликають Reflow (перекомпонування). Зміна `color` викликає лише Repaint, а `transform` та `opacity` обробляються на рівні Composite (відеокартою), що є найшвидшим."
    },

    # --- Additional specific HTML & CSS questions to reach 70 questions ---
    {
        "Question Text": "Яка структура заголовків у HTML-документі вважається семантично правильною?\n```html\n<!-- Послідовність заголовків -->\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "h1 -> h3 -> h2 -> h5",
        "Option 2": "h1 -> h2 -> h3 -> h4",
        "Option 3": "h6 -> h5 -> h4 -> h3",
        "Option 4": "Порядок заголовків не має значення для семантики",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Заголовки мають слідувати чіткій ієрархічній послідовності без пропусків рівнів (наприклад, не можна переходити від h1 одразу до h3)."
    },
    {
        "Question Text": "Який тег використовується для групування пов'язаних елементів у формі та створення рамки навколо них?\n```html\n<form>\n  <fieldset>\n    <legend>Особисті дані</legend>\n    ...\n  </fieldset>\n</form>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "<group>",
        "Option 2": "<fieldset>",
        "Option 3": "<section>",
        "Option 4": "<optgroup>",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Тег `<fieldset>` групує логічно пов'язані поля форми, а вкладений тег `<legend>` задає заголовок для цієї групи."
    },
    {
        "Question Text": "Яка властивість CSS визначає поведінку переповнення контенту блоку, якщо він виходить за межі заданих розмірів?\n```css\n.box {\n  /* overflow: ? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "display",
        "Option 2": "overflow",
        "Option 3": "clip",
        "Option 4": "visibility",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `overflow` (значення: visible, hidden, scroll, auto) визначає, чи обрізати вміст, чи показувати смуги прокручування."
    },
    {
        "Question Text": "Для чого потрібен тег `<meta charset=\"UTF-8\">` в HTML?\n```html\n<meta charset=\"UTF-8\">\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Він підключає стилі до сторінки",
        "Option 2": "Він визначає кодування символів документа для коректного відображення тексту будь-якою мовою (уникаючи 'кракозябр')",
        "Option 3": "Він вказує мову інтерфейсу для Google Translate",
        "Option 4": "Він є лінком на шрифти Google Fonts",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Мета-тег `charset=\"UTF-8\"` задає кодування Юнікод (UTF-8), що забезпечує підтримку практично всіх письмових мов світу."
    },
    {
        "Question Text": "Які з наведених тегів створюють текстові списки в HTML?\n```html\n<!-- Марковані та нумеровані списки -->\n```",
        "Question Type": "Checkbox",
        "Option 1": "<ul>",
        "Option 2": "<ol>",
        "Option 3": "<li>",
        "Option 4": "<dl>",
        "Option 5": "<list>",
        "Correct Answer": "1,2,3,4",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Теги `<ul>` (маркований), `<ol>` (нумерований) та `<dl>` (описовий) створюють списки, а `<li>` є елементом списку для `ul` та `ol`."
    },
    {
        "Question Text": "Який тег використовується для відображення попередньо відформатованого тексту, зберігаючи всі пробіли та переноси рядків моноширинним шрифтом?\n```html\n<pre>\n  Крок 1  ->  Крок 2\n      | \n  Крок 3\n</pre>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "<code>",
        "Option 2": "<pre>",
        "Option 3": "<blockquote>",
        "Option 4": "<span>",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Тег `<pre>` (preformatted text) зберігає пробіли, символи табуляції та переноси рядків так, як вони написані в коді."
    },
    {
        "Question Text": "Яке значення має атрибут `type` кнопки за замовчуванням всередині форми?\n```html\n<form>\n  <button>Надіслати</button>\n</form>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "type=\"button\"",
        "Option 2": "type=\"submit\"",
        "Option 3": "type=\"reset\"",
        "Option 4": "Залежить від браузера",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "За стандартом HTML, якщо атрибут `type` у `<button>` всередині форми не вказано, він автоматично набуває значення `submit` (відправка форми)."
    },
    {
        "Question Text": "Для чого використовується атрибут `name` у радіо-кнопках (`type=\"radio\"`)?\n```html\n<input type=\"radio\" name=\"gender\" value=\"m\">\n<input type=\"radio\" name=\"gender\" value=\"f\">\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Він задає унікальний ідентифікатор для CSS",
        "Option 2": "Він об'єднує радіо-кнопки у групу, дозволяючи обрати лише один варіант з-поміж наявних із однаковим ім'ям",
        "Option 3": "Він потрібен лише для показу підказки",
        "Option 4": "Він автоматично перетворює радіо-кнопки на чекбокси",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Атрибут `name` групує перемикачі. Тільки один перемикач з однаковим `name` може бути вибраний одночасно."
    },
    {
        "Question Text": "Який тег використовується для створення спадного списку (dropdown) у формі?\n```html\n<select>\n  <option>Варіант 1</option>\n</select>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "<dropdown>",
        "Option 2": "<select>",
        "Option 3": "<list>",
        "Option 4": "<input type=\"select\">",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Спадний список створюється за допомогою контейнера `<select>`, всередині якого розміщуються пункти `<option>`."
    },
    {
        "Question Text": "Який семантичний тег HTML5 позначає нижню частину сторінки (підвал), де зазвичай розміщують копірайт, контакти та додаткові посилання?\n```html\n<!-- Нижня область сайту -->\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "footer",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Тег `<footer>` використовується для представлення підвалу сторінки або розділу сайту."
    },
    {
        "Question Text": "Які з наведених тегів є семантичними структурними елементами HTML5?\n```html\n<!-- Оберіть нові семантичні теги макету сторінки -->\n```",
        "Question Type": "Checkbox",
        "Option 1": "<header>",
        "Option 2": "<nav>",
        "Option 3": "<main>",
        "Option 4": "<section>",
        "Option 5": "<center>",
        "Correct Answer": "1,2,3,4",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "`<header>`, `<nav>`, `<main>` та `<section>` — це сучасні семантичні теги. Тег `<center>` застарів і вилучений зі стандарту."
    },
    {
        "Question Text": "Який атрибут тегу `<video>` змушує медіафайл автоматично програватися відразу після завантаження сторінки (якщо це дозволено налаштуваннями браузера)?\n```html\n<video autoplay muted></video>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "loop",
        "Option 2": "autoplay",
        "Option 3": "controls",
        "Option 4": "preload",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Атрибут `autoplay` вказує браузеру розпочати відтворення медіафайлу автоматично. У багатьох браузерах це працює лише з атрибутом `muted` (без звуку)."
    },
    {
        "Question Text": "Який тег HTML5 використовується для групування ілюстрації (наприклад, зображення) та підпису до неї?\n```html\n<figure>\n  <img src=\"image.jpg\" alt=\"\">\n  <figcaption>Підпис до фото</figcaption>\n</figure>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "<picture>",
        "Option 2": "<figure>",
        "Option 3": "<aside>",
        "Option 4": "<details>",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Тег `<figure>` об'єднує медіаконтент та опис до нього, який задається за допомогою тегу `<figcaption>`."
    },
    {
        "Question Text": "У чому відмінність між селекторами `.item` та `#item` у CSS?\n```css\n.item { color: red; }\n#item { color: blue; }\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "`.item` — це селектор класу (можна використовувати багаторазово на сторінці), а `#item` — селектор ідентифікатора (має бути унікальним на сторінці)",
        "Option 2": "`#item` вибирає теги за назвою, а `.item` — за класом",
        "Option 3": "Клас має вищий пріоритет за ID",
        "Option 4": "Відмінностей немає",
        "Option 5": "",
        "Correct Answer": "1",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Крапка `.` позначає селектор класу, гратка `#` — селектор унікального ідентифікатора ID. Пріоритет ID значно вищий за клас."
    },
    {
        "Question Text": "Який селектор вибере лише ті параграфи `<p>`, які знаходяться безпосередньо всередині блоку `<div>` (є прямими дітьми)?\n```html\n<div>\n  <p>Дитина</p>\n  <span>\n    <p>Онук</p>\n  </span>\n</div>\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "div p",
        "Option 2": "div > p",
        "Option 3": "div + p",
        "Option 4": "div ~ p",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Дитячий селектор `>` (child combinator) вибирає лише прямих дітей елемента першого рівня вкладеності."
    },
    {
        "Question Text": "Яка властивість CSS визначає колір тексту всередині елемента?\n```css\n.text {\n  /* Яка властивість керує кольором шрифту? */: blue;\n}\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "color",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `color` визначає колір переднього плану (тексту) елемента."
    },
    {
        "Question Text": "Вам потрібно приховати елемент зі сторінки, але так, щоб він продовжував займати своє фізичне місце в макеті. Яку властивість і значення обрати?\n```css\n.hidden {\n  /* Як приховати елемент із збереженням місця? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "display: none;",
        "Option 2": "visibility: hidden;",
        "Option 3": "opacity: 1;",
        "Option 4": "position: absolute;",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`visibility: hidden;` робить елемент невидимим, але він продовжує брати участь у розмітці сторінки. На противагу, `display: none;` повністю вилучає його з потоку рендерингу."
    },
    {
        "Question Text": "Яке значення властивості `display` робить елемент блочним, але дозволяє йому обтікатися іншим текстом у рядку (гібридна поведінка)?\n```css\n.inline-block {\n  display: inline-block;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "block",
        "Option 2": "inline",
        "Option 3": "inline-block",
        "Option 4": "flex",
        "Option 5": "",
        "Correct Answer": "3",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`inline-block` поєднує поведінку рядкового елемента (стає в один рядок із сусідніми елементами) та блочного (можна задавати ширину, висоту, паддінги та маргіни)."
    },
    {
        "Question Text": "Яка одиниця виміру шрифту дорівнює поточній висоті символу 'x' у поточному шрифті?\n```css\n.text {\n  font-size: 2ex;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "ch",
        "Option 2": "ex",
        "Option 3": "em",
        "Option 4": "px",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Одиниця виміру `ex` є відносною і базується на висоті символу нижнього регістру 'x' (x-height) вибраного шрифту."
    },
    {
        "Question Text": "Як зробити текст повністю великими літерами (Caps Lock) за допомогою CSS?\n```css\n.uppercase {\n  /* Яке значення обрати? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "text-decoration: uppercase;",
        "Option 2": "text-transform: uppercase;",
        "Option 3": "font-style: bold;",
        "Option 4": "font-variant: small-caps;",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `text-transform: uppercase;` перетворює всі літери виділеного тексту на великі (прописні)."
    },
    {
        "Question Text": "Яка CSS-властивість керує стилем накреслення шрифту (наприклад, робить його курсивним)?\n```css\n.italic-text {\n  /* Як зробити текст курсивом? */: italic;\n}\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "font-style",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `font-style` зі значенням `italic` робить шрифт курсивним."
    },
    {
        "Question Text": "Як правильно підключити зовнішнє зображення на тло елемента за допомогою CSS?\n```css\n.banner {\n  background-image: url('bg.jpg');\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "background-image: src('bg.jpg');",
        "Option 2": "background-image: url('bg.jpg');",
        "Option 3": "background-image: path('bg.jpg');",
        "Option 4": "background-image: 'bg.jpg';",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Функція `url('шлях')` використовується у CSS для завантаження медіафайлів (зображень, шрифтів) у стилі."
    },
    {
        "Question Text": "Яка властивість керує тим, чи повторюється фонове зображення, якщо воно менше за розміри блоку?\n```css\n.bg {\n  /* background-repeat: ? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "background-size",
        "Option 2": "background-repeat",
        "Option 3": "background-position",
        "Option 4": "background-attachment",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `background-repeat` зі значеннями `no-repeat`, `repeat-x`, `repeat-y` визначає циклічне повторення фонової картинки."
    },
    {
        "Question Text": "Які з наведених властивостей відносяться до налаштування тіней або ефектів розмиття у CSS?\n```css\n/* Тіні та фільтри */\n```",
        "Question Type": "Checkbox",
        "Option 1": "text-shadow",
        "Option 2": "box-shadow",
        "Option 3": "filter",
        "Option 4": "backdrop-filter",
        "Option 5": "border-shadow",
        "Correct Answer": "1,2,3,4",
        "Time in seconds": "45",
        "Image Link": "",
        "Answer explanation": "Властивості `text-shadow` (тінь тексту), `box-shadow` (тінь блоку), `filter` (фільтри картинки) та `backdrop-filter` (фільтри тла під блоком) є стандартними. Властивості `border-shadow` не існує."
    },
    {
        "Question Text": "Яка властивість флекс-контейнера задає напрямок головної осі, вздовж якої вибудовуються елементи?\n```css\n.container {\n  display: flex;\n  /* flex-direction: ? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "justify-content",
        "Option 2": "flex-direction",
        "Option 3": "flex-flow",
        "Option 4": "align-items",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `flex-direction` (рядкові значення: row, row-reverse, column, column-reverse) керує орієнтацією головної осі флекс-контейнера."
    },
    {
        "Question Text": "Вам потрібно зробити так, щоб флекс-елементи рівномірно розподілили між собою весь доступний вільний простір. Яку властивість зростання та значення прописати кожному елементу?\n```css\n.item {\n  /* flex-grow: ? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "flex-grow: 0;",
        "Option 2": "flex-grow: 1;",
        "Option 3": "flex-shrink: 1;",
        "Option 4": "flex-basis: 100%;",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`flex-grow: 1;` змушує всі елементи розширюватися однаково, забираючи рівні частки залишкового простору в контейнері."
    },
    {
        "Question Text": "Яка властивість задає відстань (проміжки) між елементами у Flexbox чи Grid, не використовуючи зовнішні відступи margin?\n```css\n.container {\n  display: flex;\n  /* Яка властивість задає проміжок? */: 20px;\n}\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "gap",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `gap` (та її підвиди `row-gap`, `column-gap`) дозволяє легко створювати проміжки між сусідніми флекс/грід елементами."
    },
    {
        "Question Text": "Яка властивість Grid визначає розмір автоматично створюваних рядків (implicit grid), якщо контент виходить за рамки явно заданого шаблону?\n```css\n.grid {\n  display: grid;\n  /* grid-auto-rows: ? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "grid-template-rows",
        "Option 2": "grid-auto-rows",
        "Option 3": "grid-row-gap",
        "Option 4": "grid-auto-flow",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `grid-auto-rows` задає висоту треків для неявних рядків (тих, що створюються автоматично при додаванні контенту понад шаблон)."
    },
    {
        "Question Text": "Яке позиціонування фіксує елемент відносно вікна перегляду (viewport) браузера, залишаючи його на місці навіть при прокручуванні сторінки?\n```css\n.popup {\n  position: fixed;\n  bottom: 20px;\n  right: 20px;\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "absolute",
        "Option 2": "fixed",
        "Option 3": "sticky",
        "Option 4": "relative",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "`position: fixed` повністю вилучає елемент із загального потоку та позиціонує його відносно вікна перегляду (viewport). При скролінгу елемент не змінює положення на екрані."
    },
    {
        "Question Text": "Яка CSS-властивість керує порядком накладання позиціонованих елементів один на одного по осі Z?\n```css\n.modal {\n  /* z-index: ? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "depth-index",
        "Option 2": "z-index",
        "Option 3": "layer-order",
        "Option 4": "display-level",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `z-index` приймає цілі числа (як додатні, так і від'ємні) та визначає, які елементи перекриватимуть інші."
    },
    {
        "Question Text": "Вам потрібно застосувати 3D-поворот до елемента вздовж осі Y на 45 градусів. Яку властивість і функцію обрати?\n```css\n.box {\n  /* transform: ? */\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "transform: rotateY(45deg);",
        "Option 2": "transform: skewY(45deg);",
        "Option 3": "transition: rotateY(45deg);",
        "Option 4": "transform: turnY(0.125);",
        "Option 5": "",
        "Correct Answer": "1",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Функція `rotateY(кут)` у властивості `transform` повертає елемент у тривимірному просторі навколо вертикальної осі Y."
    },
    {
        "Question Text": "Яка CSS-властивість задає затримку перед початком виконання транзишну (анімації переходу)?\n```css\n.card {\n  /* Яка властивість відповідає за затримку? */: 1s;\n}\n```",
        "Question Type": "Fill-in-the-Blank",
        "Option 1": "transition-delay",
        "Option 2": "",
        "Option 3": "",
        "Option 4": "",
        "Option 5": "",
        "Correct Answer": "",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Властивість `transition-delay` вказує час очікування (наприклад, `1s` або `500ms`) перед стартом транзишну."
    },
    {
        "Question Text": "За допомогою якого ключового слова в медіа-запитах можна вказати тип пристроїв із друкованим виведенням (наприклад, попередній перегляд друку)?\n```css\n@media print {\n  body { background: none; }\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "screen",
        "Option 2": "print",
        "Option 3": "speech",
        "Option 4": "all",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Тип медіа `print` націлює стилі виключно на паперовий друк або режим попереднього перегляду друку у браузері."
    },
    {
        "Question Text": "Який атрибут тегу `<img>` містить список зображень різних розмірів та роздільної здатності для автоматичного вибору браузером залежно від екрана?\n```html\n<img srcset=\"small.jpg 500w, large.jpg 1000w\" src=\"fallback.jpg\" alt=\"\">\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "sizes",
        "Option 2": "srcset",
        "Option 3": "imagesrc",
        "Option 4": "src-multi",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Атрибут `srcset` передає браузеру перелік файлів та їх дескриптори ширини (`w`) або щільності пікселів (`x`) для вибору найбільш оптимального зображення."
    },
    {
        "Question Text": "Який синтаксис використовується для виклику та підстановки раніше створеної CSS-змінної?\n```css\n.card {\n  color: var(--primary-color);\n}\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "color: val(--primary-color);",
        "Option 2": "color: var(--primary-color);",
        "Option 3": "color: const(--primary-color);",
        "Option 4": "color: $primary-color;",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Змінні підставляються за допомогою CSS-функції `var(--назва-змінної)`."
    },
    {
        "Question Text": "Яка мета використання CSS Reset або Normalize.css у веб-розробці?\n```css\n/* normalize.css */\n```",
        "Question Type": "Multiple Choice",
        "Option 1": "Вони автоматично стискають CSS-коди для швидкого завантаження",
        "Option 2": "Вони зводять до мінімуму або усувають розбіжності у базових стилях браузерів за замовчуванням, створюючи однакову кросбраузерну основу",
        "Option 3": "Вони шифрують стилі від копіювання",
        "Option 4": "Вони перевіряють код на синтаксичні помилки",
        "Option 5": "",
        "Correct Answer": "2",
        "Time in seconds": "30",
        "Image Link": "",
        "Answer explanation": "Різні браузери мають свої замовчувані відступи, висоти та рамки. Reset/Normalize усуває ці відмінності, створюючи однакову стартову точку."
    }
]

# Slice to exactly 70 questions if we have more
questions = questions[:70]

# Ensure we have exactly 70 questions
print(f"Total defined questions: {len(questions)}")
if len(questions) != 70:
    print(f"Error: Expected 70 questions, but got {len(questions)}")
    exit(1)

out_dir = "tests/12.html-css"
os.makedirs(out_dir, exist_ok=True)
json_path = "tmp_questions.json"
xlsx_path = os.path.join(out_dir, "12.html-css.xlsx")

with open(json_path, "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print("Starting wayground_exporter.py...")
# Execute the exporter
result = subprocess.run(["python3", "wayground_exporter.py", json_path, "-o", xlsx_path], capture_output=True, text=True)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr)

if os.path.exists(json_path):
    os.remove(json_path)

if result.returncode == 0:
    print(f"Success! Created {xlsx_path} with 70 questions.")
else:
    print("Failed to run exporter.")
    exit(1)
